In [3]:
import pandas as pd

lora = pd.read_csv('data/submissions/submission_lora_bert_base_multilingual_uncased_sentiment.csv')
dl = pd.read_csv('data/submissions/DL_rounded.csv')
dl2 = pd.read_csv('data/submissions/DL_rounded2.csv')
transformers = pd.read_csv('data/submissions/submission_transformer-bert-base-sentiment.csv')

In [4]:
lista_votadores = [lora,dl,dl2,transformers]

voting = pd.DataFrame()
first = True
for i in range(0,len(lista_votadores)):
    dataset = lista_votadores[i]
    if i == 0:
        voting['review_id'] = dataset['review_id']
        first = False
    voting['pred'+str(i)] = dataset['stars']

In [5]:
voting_columns = voting.drop(columns=['review_id']).columns.tolist()

In [9]:
voting['stars'] = voting[voting_columns].mean(axis=1, skipna=True).round(0).astype(int)
voting[['review_id','stars']].to_csv('./data/submissions/mean_ensemble.csv', index=False)

In [10]:
voting['stars2'] =voting[voting_columns].mode(axis=1)[0]

In [11]:
voting_ensemble = voting[['review_id','stars2']].copy()
voting_ensemble['stars'] = voting_ensemble['stars2'].astype(int)
voting_ensemble = voting_ensemble.drop(columns=['stars2'])
voting_ensemble.to_csv('./data/submissions/voting_ensemble.csv', index=False)
voting_ensemble.head()

                review_id  stars
0  ieYPmCImINjPzTDFmEKBKA      5
1  QIkJ8fZ4yx_QaHahWWszAA      4
2  seR2KhblYMWg-k9zzN6aYA      5
3  BToo00Fi5pfJFA5MI2HM5g      4
4  FHJAzi1imodBit3RWK7zQA      1

In [14]:
voting[(voting.pred0 != voting.pred3)]

                     review_id  pred0  pred1  pred2  pred3  stars  stars2
8       6Iq0XlswkE30fBO45VkGpA      5    5.0    4.0      4      4     4.0
15      Ps2Zo1S9spCD7YQXdOv9Qw      3    3.0    3.0      2      3     3.0
17      QQ_VMiyncUWxwtVRwcX61Q      1    1.0    2.0      2      2     1.0
40      3535nJIRqVEMrvsUXRH4Hw      5    4.0    3.0      4      4     4.0
42      VuEAPlPUyLPmMhz4EnYwNA      5    4.0    4.0      2      4     4.0
...                        ...    ...    ...    ...    ...    ...     ...
414746  GKnvCuaDcwtfDffBresbXA      2    2.0    2.0      3      2     2.0
414747  v_Wc_PexkWznbQZOtQETzg      3    4.0    4.0      4      4     4.0
414755  kUAgE9ksjxLABPbP03SOgA      4    4.0    4.0      3      4     4.0
414760  5VF1OSReEKAJS3z7lc0VRg      4    4.0    4.0      5      4     4.0
414764  tWIjow_Ix8MFHAnDs47OYw      5    4.0    3.0      4      4     4.0

[81871 rows x 7 columns]

In [16]:
voting[(voting.pred0 != voting.pred1)&(voting.pred1 == voting.pred2)]

                     review_id  pred0  pred1  pred2  pred3  stars  stars2
10      plGsCrfyraVfB4wiuEE2tA      4    5.0    5.0      4      4     4.0
13      _ktmQhiwojd1gKhETTHYfQ      3    4.0    4.0      3      4     3.0
19      zMhbXDNMR8b9TpttXVKrxw      5    2.0    2.0      5      4     2.0
27      9UMLgNaw-efsVphIJvt2pg      2    3.0    3.0      2      2     2.0
31      Eib0OPdQy7mNJ5i54-2fhA      5    4.0    4.0      5      4     4.0
...                        ...    ...    ...    ...    ...    ...     ...
414741  VUsnGtW_4ws2VNCR5-HYTQ      4    5.0    5.0      5      5     5.0
414745  dgvCO7Z8fbXQrzWUMf21ug      5    4.0    4.0      5      4     4.0
414747  v_Wc_PexkWznbQZOtQETzg      3    4.0    4.0      4      4     4.0
414748  eJP1TwkzoIHg9TF0PM84XA      5    4.0    4.0      5      4     4.0
414762  zQLW0mkqDtmseg8pl-zbNA      3    4.0    4.0      3      4     3.0

[95579 rows x 7 columns]

In [18]:
import numpy as np

voting['stars3'] = np.where(voting['pred1'] == voting['pred2'], voting['pred1'], voting['pred0'])

In [19]:
voting_ensemble = voting[['review_id','stars3']].copy()
voting_ensemble['stars'] = voting_ensemble['stars3'].astype(int)
voting_ensemble = voting_ensemble.drop(columns=['stars3'])
voting_ensemble.to_csv('./data/submissions/ensemble_loraNotEqual.csv', index=False)
voting_ensemble.head()

                review_id  stars
0  ieYPmCImINjPzTDFmEKBKA      5
1  QIkJ8fZ4yx_QaHahWWszAA      4
2  seR2KhblYMWg-k9zzN6aYA      5
3  BToo00Fi5pfJFA5MI2HM5g      4
4  FHJAzi1imodBit3RWK7zQA      1