In [1]:
import pandas as pd

lora = pd.read_csv('data/submissions/submission_lora_bert_base_multilingual_uncased_sentiment.csv')
dl = pd.read_csv('data/submissions/DL_rounded.csv')

In [3]:
lora

                     review_id  stars
0       ieYPmCImINjPzTDFmEKBKA      5
1       QIkJ8fZ4yx_QaHahWWszAA      4
2       seR2KhblYMWg-k9zzN6aYA      5
3       BToo00Fi5pfJFA5MI2HM5g      4
4       FHJAzi1imodBit3RWK7zQA      1
...                        ...    ...
414760  5VF1OSReEKAJS3z7lc0VRg      4
414761  N_yTSNrcGzGUSFPyIhAZ-g      5
414762  zQLW0mkqDtmseg8pl-zbNA      3
414763  DspB5yysBWRlFe01j_LzeA      5
414764  tWIjow_Ix8MFHAnDs47OYw      5

[414765 rows x 2 columns]

In [ ]:
lista_votadores = [lora,dl]

voting = pd.DataFrame()
first = True
for i in range(0,len(lista_votadores)):
    dataset = lista_votadores[i]
    if i == 0:
        voting['review_id'] = dataset['review_id']
        first = False
    voting['pred'+str(i)] = dataset['stars']

0
1

In [ ]:
voting_columns = voting.drop(columns=['review_id']).columns.tolist()

0         5
1         4
2         5
3         4
4         1
         ..
414760    4
414761    5
414762    4
414763    5
414764    4
Length: 414765, dtype: int32

In [ ]:
voting['stars'] = voting[voting_columns].mean(axis=1, skipna=True).round(0).astype(int)
voting.to_csv('mean_samples.csv', index=False)

In [ ]:
voting['stars2'] =voting[voting_columns].mode(axis=1)[0]
voting.to_csv('voting_samples.csv', index=False)

In [20]:
voting

                     review_id  pred0  pred1  stars  stars2
0       ieYPmCImINjPzTDFmEKBKA      5    5.0      5     5.0
1       QIkJ8fZ4yx_QaHahWWszAA      4    4.0      4     4.0
2       seR2KhblYMWg-k9zzN6aYA      5    5.0      5     5.0
3       BToo00Fi5pfJFA5MI2HM5g      4    3.0      4     3.0
4       FHJAzi1imodBit3RWK7zQA      1    1.0      1     1.0
...                        ...    ...    ...    ...     ...
414760  5VF1OSReEKAJS3z7lc0VRg      4    4.0      4     4.0
414761  N_yTSNrcGzGUSFPyIhAZ-g      5    5.0      5     5.0
414762  zQLW0mkqDtmseg8pl-zbNA      3    4.0      4     3.0
414763  DspB5yysBWRlFe01j_LzeA      5    5.0      5     5.0
414764  tWIjow_Ix8MFHAnDs47OYw      5    4.0      4     4.0

[414765 rows x 5 columns]